[python]
python_version = "3.13.0" 


[environment]
path = ".venv\Scripts\activate" 


[environment_variables]
[command]
run = "python manage.py runserver" 


[dependencies]
Django==5.1.4
	-asgiref==3.8.1
	-sqlparse==0.5.3
	-tzdata==2024.2
django-admin-interface==0.29.2
	-django-colorfield==0.11.0
		-pillow==11.0.0
	-python-slugify==8.0.4
		-text-unidecode==1.3
django-flat-responsive==2.0
django-flat-theme==1.1.4
