# Generated by Django 4.0 on 2021-12-15 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id_no', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='blogImage/')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id_no', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('parent_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id_no', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=1000)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Custom_User',
            fields=[
                ('id_no', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('userimage', models.ImageField(default='userImage/01.jpg', upload_to='userImage/')),
                ('mobileno', models.CharField(default='', max_length=20)),
                ('profession', models.CharField(default='', max_length=100)),
                ('userbio', models.TextField(max_length=222)),
                ('address', models.TextField(default='Earth')),
                ('link_linkedin', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('link_facebook', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('link_insta', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('link_youtube', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('link_website', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('link_twitter', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id_no', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team_Member',
            fields=[
                ('id_no', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(choices=[('CEO', '1 CEO'), ('Product Manager', '2 Product Manager'), ('Accountent', '3 Accountent'), ('Assistent Manager', '4 Assistent Manager')], default='CEO', max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
                ('ratings', models.CharField(choices=[('d', '1'), ('dy', '2'), ('dty', '3'), ('dhyf', '4'), ('dykfg', '5')], default='1', max_length=10)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id_no', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id_no', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.comment')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.custom_user')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.custom_user'),
        ),
    ]
