# Generated by Django 5.1.4 on 2024-12-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='link_facebook',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='link_insta',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='link_linkedin',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='link_twitter',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='link_website',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='link_youtube',
        ),
    ]
