# Generated by Django 4.0 on 2021-12-15 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_comment_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.custom_user'),
        ),
    ]
