# Generated by Django 4.0 on 2021-12-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_comment_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent_blog',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='uploader',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='username',
        ),
        migrations.DeleteModel(
            name='Faq',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='parent_comment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='user',
        ),
        migrations.DeleteModel(
            name='Team_Member',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Custom_User',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
