# Generated by Django 4.0 on 2021-12-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='userimage',
            field=models.ImageField(default='userImage/01.jpg', upload_to='media/userImage/'),
        ),
    ]
