# Generated by Django 4.0 on 2021-12-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_blog_slug_blog_category_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='user',
        ),
    ]
