# Generated by Django 4.0 on 2021-12-21 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_subscribe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.comment'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
