# Generated by Django 3.2.6 on 2021-12-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_reportcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportComment',
        ),
    ]
