# Generated by Django 3.2.6 on 2021-12-23 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0015_delete_reportcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='liker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Like_uploader_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
