# Generated by Django 3.2.6 on 2021-12-23 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0016_blog_liker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='liker',
        ),
        migrations.AddField(
            model_name='blog',
            name='liker',
            field=models.ManyToManyField(blank=True, null=True, related_name='Like_uploader_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
