# Generated by Django 3.2.6 on 2021-12-23 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0017_auto_20211223_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='liker',
            field=models.ManyToManyField(related_name='Like_uploader_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
