# Generated by Django 3.2.6 on 2021-12-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_blog_liker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='liker',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
    ]
