# Generated by Django 4.0.4 on 2022-04-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20211223_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.TextField(max_length=100),
        ),
    ]
