# Generated by Django 4.0.4 on 2022-04-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='ok', unique=True),
            preserve_default=False,
        ),
    ]
